SELECT
CAB.NUNOTA,
TO_CHAR(CAB.DTNEG,'YYYY-MM-DD') DTNEG,
CAB.NUMNOTA,
T.CODTIPOPER,
T.DESCROPER,
T.TIPMOV,
CID.NOMECID,
UF.UF,
PAR.CEP,
sankhya.FORMATAR_CPF_CNPJ(PAR.CGC_CPF) AS CPF,
PAR.RAZAOSOCIAL,
NVL(
    ROUND(
        NVL(CAB.VLRNOTA,0) *
        (
            (NVL(ITE.QTDNEG,0) * NVL(ITE.VLRUNIT,0)) / NULLIF(
                SUM(NVL(ITE.QTDNEG,0) * NVL(ITE.VLRUNIT,0))
                    OVER (PARTITION BY CAB.NUNOTA),
                0
            )
        ),
        2
    ),
    0
) VLRNOTA,
PRO.CODPROD,
PRO.DESCRPROD,
ITE.SEQUENCIA,
ITE.QTDNEG,
PRO.FABRICANTE,
PRO.AD_LINHA,
NVL(TRUNC(ITE.VLRUNIT,2),0) VLRUNIT,
TRA.RAZAOSOCIAL AS TRANSPORTADORA,
NVL(NF.NUMNOTA,0) AS NRONF,
NVL(TRUNC(NVL(NF.VLRFRETE,0),2),0) AS VLRFRETE,
NVL(
    ROUND(
        NVL(CAB.VLRNOTA,0) *
        (
            (NVL(ITE.QTDNEG,0) * NVL(ITE.VLRUNIT,0)) / NULLIF(
                SUM(NVL(ITE.QTDNEG,0) * NVL(ITE.VLRUNIT,0))
                    OVER (PARTITION BY CAB.NUNOTA),
                0
            )
        ),
        2
    ),
    0
) VLRNOTA_NF,
VEN.APELIDO,
NVL(TRUNC(VEN.COMGER,2),0) COMGER,
NVL(TRUNC(CAB.VLRNOTA / 100 * VEN.COMGER,2),0) AS COMISSAO,
TO_CHAR(sysdate, 'YYYY-MM-DD HH24:MI:SS') DATAEXPORT
FROM SANKHYA.TGFCAB CAB
INNER JOIN SANKHYA.TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN SANKHYA.TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN SANKHYA.TGFTOP T ON CAB.CODTIPOPER = T.CODTIPOPER AND CAB.DHTIPOPER = T.DHALTER
INNER JOIN SANKHYA.TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN SANKHYA.TSICID CID ON PAR.CODCID = CID.CODCID
INNER JOIN SANKHYA.TSIUFS UF ON CID.UF = UF.CODUF
LEFT JOIN SANKHYA.TGFVAR V ON ITE.NUNOTA = V.NUNOTA AND ITE.SEQUENCIA = V.SEQUENCIA
LEFT JOIN SANKHYA.TGFITE INF ON V.NUNOTAORIG = INF.NUNOTA AND V.SEQUENCIAORIG = INF.SEQUENCIA
LEFT JOIN SANKHYA.TGFCAB NF ON INF.NUNOTA = NF.NUNOTA
LEFT JOIN SANKHYA.TGFPAR TRA ON NF.CODPARCTRANSP = TRA.CODPARC
LEFT JOIN SANKHYA.TGFVEN VEN ON NF.CODVEND = VEN.CODVEND
WHERE (T.TIPMOV = 'V' OR T.TIPMOV = 'D')
AND CAB.DTNEG >= TO_DATE(TO_CHAR(sysdate, 'YYYY-MM-DD'), 'YYYY-MM-DD') - interval '90' day(3);
