SET PAGESIZE 200
SET LINESIZE 300
SET FEEDBACK ON
SET VERIFY OFF
SET HEADING ON

PROMPT === IXN ===
SELECT i.NUARQUIVO,
       i.NUNOTA AS NUNOTA_FAT,
       i.NUMNOTA AS NUMNOTA_XML,
       i.STATUS,
       i.AD_NUNOTAORIG AS NUNOTA_PED,
       SUBSTR(i.DETALHESIMPORTACAO,1,500) AS LOG_500
  FROM SANKHYA.TGFIXN i
 WHERE i.NUARQUIVO = 1133030;

PROMPT === CAB FAT + PED ===
SELECT c.NUNOTA,
       c.TIPMOV,
       c.CODEMP,
       c.NUMNOTA,
       c.PENDENTE,
       c.AD_NRONTOAORIGEM,
       c.AD_NUNOTADEV,
       c.STATUSNFE,
       c.VLRNOTA,
       c.DTNEG
  FROM SANKHYA.TGFCAB c
 WHERE c.NUNOTA IN (
       SELECT i.NUNOTA FROM SANKHYA.TGFIXN i WHERE i.NUARQUIVO = 1133030
       UNION
       SELECT i.AD_NUNOTAORIG FROM SANKHYA.TGFIXN i WHERE i.NUARQUIVO = 1133030
 )
 ORDER BY c.TIPMOV, c.NUNOTA;

PROMPT === TGFVAR (FAT->PED) ===
SELECT v.NUNOTA,
       v.NUNOTAORIG,
       COUNT(*) AS QTD_ITENS
  FROM SANKHYA.TGFVAR v
 WHERE v.NUNOTA = (SELECT i.NUNOTA FROM SANKHYA.TGFIXN i WHERE i.NUARQUIVO = 1133030)
 GROUP BY v.NUNOTA, v.NUNOTAORIG
 ORDER BY v.NUNOTAORIG;

EXIT
