connect jackson/"kiriku#1060"@//127.0.0.1:11521/skwpdb.sub03311532240.vncbela.oraclevcn.com
set pages 200 lines 200 trimspool on feedback on verify off
WITH s_last AS (
    SELECT s.NUNOTA, s.DTALTER, s.CODMICRO,
           ROW_NUMBER() OVER (PARTITION BY s.NUNOTA ORDER BY s.DTALTER DESC) AS rn
    FROM SANKHYA.AD_STATUSINTELIPOST s
),
rel_base AS (
    SELECT
        REL.NUNOTA,
        REL.SEQUENCIA,
        REL.DTFATUR,
        NVL(REL.TRANSPORTADORA,'SEM TRANSPORTADORA') AS TRANSPORTADORA,
        CASE
            WHEN HIST.SITUACAO IS NOT NULL THEN SANKHYA.OPTION_LABEL('AD_BHZHIST', 'SITUACAO', HIST.SITUACAO)
            WHEN REL.DTENTREGANF IS NOT NULL THEN 'Entregue'
            ELSE 'Em Rota'
        END AS SITUACAO
    FROM SANKHYA.BHZ_RELTRANSP REL
    LEFT JOIN SANKHYA.AD_BHZHIST HIST
           ON HIST.NUNOTA = REL.NUNOTA
          AND (REL.SEQUENCIA = HIST.SEQUENCIA OR HIST.SEQUENCIA IS NULL)
          AND HIST.SEQ = (
                SELECT MAX(H2.SEQ)
                FROM SANKHYA.AD_BHZHIST H2
                WHERE H2.NUNOTA = REL.NUNOTA
                  AND (REL.SEQUENCIA = H2.SEQUENCIA OR H2.SEQUENCIA IS NULL)
          )
    INNER JOIN SANKHYA.TGFPAR PAR ON PAR.CODPARC = REL.CODPARC
    INNER JOIN SANKHYA.TGFITE ITE ON ITE.NUNOTA = REL.NUNOTA AND ITE.SEQUENCIA = REL.SEQUENCIA
    WHERE REL.DTFATUR >= TO_DATE('01/01/2025', 'DD/MM/YYYY')
),
base_filtrada AS (
  SELECT rb.*, ms.NOMEPADRAO
  FROM rel_base rb
  LEFT JOIN s_last s
         ON s.NUNOTA = rb.NUNOTA
        AND s.rn = 1
  LEFT JOIN SANKHYA.AD_MICROSTATUSINTELIPOST ms
         ON ms.CODIGO = s.CODMICRO
  WHERE UPPER(NVL(ms.NOMEPADRAO, '')) NOT LIKE '%ENTREGUE NO DESTINO%'
)
SELECT
  TRANSPORTADORA,
  COUNT(*) AS QTD,
  MIN(DTFATUR) AS MIN_DTFATUR,
  MAX(DTFATUR) AS MAX_DTFATUR,
  SUM(CASE WHEN SITUACAO IN ('Bloqueio','Coleta','Devolução','Em Rota','Em Tratativa','Devolucao','Extravio') THEN 1 ELSE 0 END) AS QTD_SITUACAO_OK,
  SUM(CASE WHEN REGEXP_LIKE(UPPER(REGEXP_REPLACE(NVL(TRANSPORTADORA,''), '[^A-Z0-9]', '')), '(SHPX|SPX)') THEN 1 ELSE 0 END) AS QTD_SHPX
FROM base_filtrada
WHERE UPPER(TRANSPORTADORA) LIKE '%TRILOG%'
   OR UPPER(TRANSPORTADORA) LIKE '%AVIOES%'
   OR UPPER(TRANSPORTADORA) LIKE '%GENEROSO%'
GROUP BY TRANSPORTADORA
ORDER BY TRANSPORTADORA;
exit
