
WITH REL_FILTRADO AS (
  SELECT REL.*
    FROM SANKHYA.BHZ_RELTRANSP REL
   WHERE REL.EXPEDIDO >= TO_DATE(TO_CHAR(SYSDATE, 'DD/MM/YYYY'), 'DD/MM/YYYY') - INTERVAL '100' DAY(3)
     AND REL.CODTIPOPER IN
         ('3298','3296','3215','46','47','45','49','43','33','3250','3121','3209','23',
          '3211','71','3218','3231','3120','3124','87','3229','44','3223','3228','3210',
          '3226','3202','3233','2137','85','84','2138','86','73','72','3227','3299',
          '3200','3206','3224','3213','3234','3232','3225','3207','3297','3208','3212','3230')
     AND REL.CODPARCTRANSP NOT IN (401961, 271827, 18789, 422862, 16, 0)
     AND (
           REL.CODPARCTRANSP = 918566
           OR REL.CODPARCTRANSP IN (
                 SELECT CODPARC
                   FROM SANKHYA.TGFPAR
                  WHERE AD_CODTRANSPINT IN
                    ('285038','285038','519252','536527','386550','180173','241789',
                     '220344','220344','180168','180096','224984','224984','180152',
                     '536524','462086','548686','281091','288270','299851','180095',
                     '519553','481118','1058304','64749','1062294')
               )
         )
     AND (DTENTREGANF IS NULL OR 'N' = 'N')
     AND REL.CODEMP IN ('1','2','3','4','5','6')
),
REL_DEDUP AS (
  SELECT *
    FROM (
      SELECT REL.*,
             ROW_NUMBER() OVER (
               PARTITION BY REL.NUNOTA, REL.SEQUENCIA
               ORDER BY REL.ROWID DESC
             ) AS RN
        FROM REL_FILTRADO REL
    )
   WHERE RN = 1
)
SELECT
  REL.CODEMP,
  REL.APELIDO,
  REL.BH_DTPEDAPROV,
  REL.DTFATUR,
  REL.SKU,
  REL.DESCRPROD,
  REL.TIME,
  REL.EXPEDIDO,
  REL.BH_DTENTREGA,
  REL.DTRANSP,
  REL.DIFERENCA_EM_DIAS,
  REL.DIFERENCA_EM_DIASBELA,
  REL.DIF_DATAS,
  REL.PRAZOENT,
  REL.DTENTREGANF,
  REL.TRANSPORTADORA,
  REL.NUMNOTA,
  REL.CODPARC,
  TRIM(REPLACE(REPLACE(REL.PARCEIRO, CHR(10), ' '), CHR(13), ' ')) AS PARCEIRO,
  REL.NOMECID,
  REL.UF,
  REL.VLRNOTA,
  REL.VLRFRETE,
  REL.NUNOTA,
  REL.BH_CODEMKT,
  REL.STATUS,
  REL.NUNOTAPED,
  REL.DESCROPER,
  REL.CEP,
  TRIM(REPLACE(REPLACE(REL.ENDERECO, CHR(10), ' '), CHR(13), ' ')) AS ENDERECO,
  REL.TELEFONE,
  REL.CODPARCTRANSP,
  REL.PARCONT,
  REL.SITTRANSP,
  REL.SITBELA,
  REL.DTNEG,
  REL.CODTIPOPER,
  REL.SEQUENCIA,
  REL.TEMCTE,
  REL.CUSTOFRETE,
  REL.AD_DIASENTREGA,
  ITE.QTDNEG,
  PAR.CGC_CPF AS CPF,
  NVL(TRAT.DESCRICAO, ' ') AS TRATATIVA,
  NVL(HIST.OBSERVACAO, ' ') AS OBSERVACAO,
  HIST.DHINC AS ULTINTERACAO,
  CASE
    WHEN HIST.SITUACAO IS NOT NULL
      THEN SANKHYA.OPTION_LABEL('AD_BHZHIST', 'SITUACAO', HIST.SITUACAO)
    WHEN DTENTREGANF IS NOT NULL
      THEN 'Entregue'
    ELSE 'Em Rota'
  END AS SITUACAO,
  CASE
    WHEN DIFERENCA_EM_DIAS > 0 AND STATUS <> 'Devolucao' THEN 'RED'
    WHEN DIF_DATAS < 0 AND STATUS <> 'Devolucao' THEN '#B8860B'
    ELSE NULL
  END AS FGCOLOR,
  CASE
    WHEN CASE
           WHEN HIST.SITUACAO IS NOT NULL
             THEN SANKHYA.OPTION_LABEL('AD_BHZHIST', 'SITUACAO', HIST.SITUACAO)
           WHEN DTENTREGANF IS NOT NULL
             THEN 'Entregue'
           ELSE 'Em Rota'
         END IN ('Em Rota', 'Entregue', 'Devolvido', 'Indeniza  o Paga')
      THEN 'DENTRO DO PRAZO'
    WHEN ROUND((SYSDATE - HIST.DHINC) * 24, 0) > TRAT.SLA
      THEN 'FORA DO PRAZO'
    ELSE 'DENTRO DO PRAZO'
  END AS STATUSSLA,
  CASE
    WHEN REL.CODPARCTRANSP IN (220344, 224984) THEN 'Meli'
    WHEN REL.CODPARCTRANSP IN (285038) THEN 'Amazon'
    ELSE 'Proprio'
  END AS TIPENV,
  CASE
    WHEN REL.CODPARCTRANSP IN (220344, 224984) THEN 'M'
    WHEN REL.CODPARCTRANSP IN (285038) THEN 'A'
    ELSE 'P'
  END AS TIPENVFILTRO,
  OTRAT.DESCRICAO AS ORIGEMTRAT,
  REL.CUSTOFRETE - REL.VLRFRETE AS RESULTFRETE,
  USU.NOMEUSU AS ULTUSUINTER
FROM REL_DEDUP REL
LEFT JOIN SANKHYA.AD_BHZHIST HIST
       ON HIST.NUNOTA = REL.NUNOTA
      AND (REL.SEQUENCIA = HIST.SEQUENCIA OR HIST.SEQUENCIA IS NULL)
      AND HIST.SEQ = (SELECT MAX(SEQ)
                        FROM SANKHYA.AD_BHZHIST
                       WHERE NUNOTA = REL.NUNOTA
                         AND (REL.SEQUENCIA = SEQUENCIA OR SEQUENCIA IS NULL))
LEFT JOIN SANKHYA.AD_BHZOTRAT OTRAT
       ON OTRAT.CODOTRAT = HIST.CODOTRAT
LEFT JOIN SANKHYA.AD_BHZTRAT TRAT
       ON TRAT.CODTRAT = HIST.CODTRAT
LEFT JOIN SANKHYA.TSIUSU USU
       ON USU.CODUSU = HIST.CODUSU
INNER JOIN SANKHYA.TGFPAR PAR
        ON PAR.CODPARC = REL.CODPARC
INNER JOIN SANKHYA.TGFITE ITE
        ON ITE.NUNOTA = REL.NUNOTA
       AND ITE.SEQUENCIA = REL.SEQUENCIA

